spring.application.name=Ai_invoice_extractor

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_invoice_extractor
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true